/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMeRouteImport } from './routes/app.me'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as AppMeIndexRouteImport } from './routes/app.me.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppMePreferencesRouteImport } from './routes/app.me.preferences'
import { Route as AppMeNotificationsRouteImport } from './routes/app.me.notifications'
import { Route as AppDmUserIdRouteImport } from './routes/app.dm.$userId'
import { Route as AppCChannelIdRouteImport } from './routes/app.c.$channelId'
import { Route as AppAdminSmtpRouteImport } from './routes/app.admin.smtp'
import { Route as AppAdminSlackRouteImport } from './routes/app.admin.slack'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppAdminMembersRouteImport } from './routes/app.admin.members'
import { Route as AppAdminInvitesRouteImport } from './routes/app.admin.invites'
import { Route as AppAdminIntegrationsRouteImport } from './routes/app.admin.integrations'
import { Route as AppAdminEmailRouteImport } from './routes/app.admin.email'
import { Route as AppAdminChannelsRouteImport } from './routes/app.admin.channels'
import { Route as ApiIntegrationsOauthCallbackRouteImport } from './routes/api.integrations.oauth.callback'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMeIndexRoute = AppMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMeRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppMePreferencesRoute = AppMePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppMeRoute,
} as any)
const AppMeNotificationsRoute = AppMeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppMeRoute,
} as any)
const AppDmUserIdRoute = AppDmUserIdRouteImport.update({
  id: '/dm/$userId',
  path: '/dm/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppCChannelIdRoute = AppCChannelIdRouteImport.update({
  id: '/c/$channelId',
  path: '/c/$channelId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSmtpRoute = AppAdminSmtpRouteImport.update({
  id: '/smtp',
  path: '/smtp',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSlackRoute = AppAdminSlackRouteImport.update({
  id: '/slack',
  path: '/slack',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMembersRoute = AppAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminInvitesRoute = AppAdminInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminIntegrationsRoute = AppAdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEmailRoute = AppAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminChannelsRoute = AppAdminChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiIntegrationsOauthCallbackRoute =
  ApiIntegrationsOauthCallbackRouteImport.update({
    id: '/api/integrations/oauth/callback',
    path: '/api/integrations/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/todos': typeof TodosRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/me': typeof AppMeRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/channels': typeof AppAdminChannelsRoute
  '/app/admin/email': typeof AppAdminEmailRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/invites': typeof AppAdminInvitesRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/slack': typeof AppAdminSlackRoute
  '/app/admin/smtp': typeof AppAdminSmtpRoute
  '/app/c/$channelId': typeof AppCChannelIdRoute
  '/app/dm/$userId': typeof AppDmUserIdRoute
  '/app/me/notifications': typeof AppMeNotificationsRoute
  '/app/me/preferences': typeof AppMePreferencesRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/me/': typeof AppMeIndexRoute
  '/api/integrations/oauth/callback': typeof ApiIntegrationsOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/todos': typeof TodosRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app': typeof AppIndexRoute
  '/app/admin/channels': typeof AppAdminChannelsRoute
  '/app/admin/email': typeof AppAdminEmailRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/invites': typeof AppAdminInvitesRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/slack': typeof AppAdminSlackRoute
  '/app/admin/smtp': typeof AppAdminSmtpRoute
  '/app/c/$channelId': typeof AppCChannelIdRoute
  '/app/dm/$userId': typeof AppDmUserIdRoute
  '/app/me/notifications': typeof AppMeNotificationsRoute
  '/app/me/preferences': typeof AppMePreferencesRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/me': typeof AppMeIndexRoute
  '/api/integrations/oauth/callback': typeof ApiIntegrationsOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/todos': typeof TodosRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/me': typeof AppMeRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/channels': typeof AppAdminChannelsRoute
  '/app/admin/email': typeof AppAdminEmailRoute
  '/app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/app/admin/invites': typeof AppAdminInvitesRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/slack': typeof AppAdminSlackRoute
  '/app/admin/smtp': typeof AppAdminSmtpRoute
  '/app/c/$channelId': typeof AppCChannelIdRoute
  '/app/dm/$userId': typeof AppDmUserIdRoute
  '/app/me/notifications': typeof AppMeNotificationsRoute
  '/app/me/preferences': typeof AppMePreferencesRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/me/': typeof AppMeIndexRoute
  '/api/integrations/oauth/callback': typeof ApiIntegrationsOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/todos'
    | '/accept-invite/$token'
    | '/app/admin'
    | '/app/me'
    | '/app/'
    | '/app/admin/channels'
    | '/app/admin/email'
    | '/app/admin/integrations'
    | '/app/admin/invites'
    | '/app/admin/members'
    | '/app/admin/settings'
    | '/app/admin/slack'
    | '/app/admin/smtp'
    | '/app/c/$channelId'
    | '/app/dm/$userId'
    | '/app/me/notifications'
    | '/app/me/preferences'
    | '/app/admin/'
    | '/app/me/'
    | '/api/integrations/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/todos'
    | '/accept-invite/$token'
    | '/app'
    | '/app/admin/channels'
    | '/app/admin/email'
    | '/app/admin/integrations'
    | '/app/admin/invites'
    | '/app/admin/members'
    | '/app/admin/settings'
    | '/app/admin/slack'
    | '/app/admin/smtp'
    | '/app/c/$channelId'
    | '/app/dm/$userId'
    | '/app/me/notifications'
    | '/app/me/preferences'
    | '/app/admin'
    | '/app/me'
    | '/api/integrations/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/todos'
    | '/accept-invite/$token'
    | '/app/admin'
    | '/app/me'
    | '/app/'
    | '/app/admin/channels'
    | '/app/admin/email'
    | '/app/admin/integrations'
    | '/app/admin/invites'
    | '/app/admin/members'
    | '/app/admin/settings'
    | '/app/admin/slack'
    | '/app/admin/smtp'
    | '/app/c/$channelId'
    | '/app/dm/$userId'
    | '/app/me/notifications'
    | '/app/me/preferences'
    | '/app/admin/'
    | '/app/me/'
    | '/api/integrations/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TodosRoute: typeof TodosRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  ApiIntegrationsOauthCallbackRoute: typeof ApiIntegrationsOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/me/': {
      id: '/app/me/'
      path: '/'
      fullPath: '/app/me/'
      preLoaderRoute: typeof AppMeIndexRouteImport
      parentRoute: typeof AppMeRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/me/preferences': {
      id: '/app/me/preferences'
      path: '/preferences'
      fullPath: '/app/me/preferences'
      preLoaderRoute: typeof AppMePreferencesRouteImport
      parentRoute: typeof AppMeRoute
    }
    '/app/me/notifications': {
      id: '/app/me/notifications'
      path: '/notifications'
      fullPath: '/app/me/notifications'
      preLoaderRoute: typeof AppMeNotificationsRouteImport
      parentRoute: typeof AppMeRoute
    }
    '/app/dm/$userId': {
      id: '/app/dm/$userId'
      path: '/dm/$userId'
      fullPath: '/app/dm/$userId'
      preLoaderRoute: typeof AppDmUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/c/$channelId': {
      id: '/app/c/$channelId'
      path: '/c/$channelId'
      fullPath: '/app/c/$channelId'
      preLoaderRoute: typeof AppCChannelIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/smtp': {
      id: '/app/admin/smtp'
      path: '/smtp'
      fullPath: '/app/admin/smtp'
      preLoaderRoute: typeof AppAdminSmtpRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/slack': {
      id: '/app/admin/slack'
      path: '/slack'
      fullPath: '/app/admin/slack'
      preLoaderRoute: typeof AppAdminSlackRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/members': {
      id: '/app/admin/members'
      path: '/members'
      fullPath: '/app/admin/members'
      preLoaderRoute: typeof AppAdminMembersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/invites': {
      id: '/app/admin/invites'
      path: '/invites'
      fullPath: '/app/admin/invites'
      preLoaderRoute: typeof AppAdminInvitesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/integrations': {
      id: '/app/admin/integrations'
      path: '/integrations'
      fullPath: '/app/admin/integrations'
      preLoaderRoute: typeof AppAdminIntegrationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/email': {
      id: '/app/admin/email'
      path: '/email'
      fullPath: '/app/admin/email'
      preLoaderRoute: typeof AppAdminEmailRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/channels': {
      id: '/app/admin/channels'
      path: '/channels'
      fullPath: '/app/admin/channels'
      preLoaderRoute: typeof AppAdminChannelsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/integrations/oauth/callback': {
      id: '/api/integrations/oauth/callback'
      path: '/api/integrations/oauth/callback'
      fullPath: '/api/integrations/oauth/callback'
      preLoaderRoute: typeof ApiIntegrationsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminChannelsRoute: typeof AppAdminChannelsRoute
  AppAdminEmailRoute: typeof AppAdminEmailRoute
  AppAdminIntegrationsRoute: typeof AppAdminIntegrationsRoute
  AppAdminInvitesRoute: typeof AppAdminInvitesRoute
  AppAdminMembersRoute: typeof AppAdminMembersRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminSlackRoute: typeof AppAdminSlackRoute
  AppAdminSmtpRoute: typeof AppAdminSmtpRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminChannelsRoute: AppAdminChannelsRoute,
  AppAdminEmailRoute: AppAdminEmailRoute,
  AppAdminIntegrationsRoute: AppAdminIntegrationsRoute,
  AppAdminInvitesRoute: AppAdminInvitesRoute,
  AppAdminMembersRoute: AppAdminMembersRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminSlackRoute: AppAdminSlackRoute,
  AppAdminSmtpRoute: AppAdminSmtpRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppMeRouteChildren {
  AppMeNotificationsRoute: typeof AppMeNotificationsRoute
  AppMePreferencesRoute: typeof AppMePreferencesRoute
  AppMeIndexRoute: typeof AppMeIndexRoute
}

const AppMeRouteChildren: AppMeRouteChildren = {
  AppMeNotificationsRoute: AppMeNotificationsRoute,
  AppMePreferencesRoute: AppMePreferencesRoute,
  AppMeIndexRoute: AppMeIndexRoute,
}

const AppMeRouteWithChildren = AppMeRoute._addFileChildren(AppMeRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppMeRoute: typeof AppMeRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCChannelIdRoute: typeof AppCChannelIdRoute
  AppDmUserIdRoute: typeof AppDmUserIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppMeRoute: AppMeRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCChannelIdRoute: AppCChannelIdRoute,
  AppDmUserIdRoute: AppDmUserIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TodosRoute: TodosRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  ApiIntegrationsOauthCallbackRoute: ApiIntegrationsOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
